import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['typescript'],
  categories: {
    correctness: 'off',
  },
  options: {
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: true,
  },
  jsPlugins: [
    {
      name: 'eslint-js',
      specifier: 'oxlint-plugin-eslint',
    },
  ],
  env: {
    browser: true,
    builtin: true,
    node: true,
  },
  ignorePatterns: [
    '.*/**',
    'artifacts/**',
    'build/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
    'presets/**/*',
    '!presets/baseline/**',
    'tmp/**',
    'scripts/playwright-web-server.ts',
  ],
  rules: {
    'for-direction': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-else-if': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-global-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-unassigned-vars': 'error',
    'no-unexpected-multiline': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'preserve-caught-error': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'no-array-constructor': 'error',
    'no-unused-expressions': 'error',
    'no-useless-constructor': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-invalid-void-type': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
    'typescript/unified-signatures': 'error',
    'no-undef': 'error',
    'no-useless-assignment': 'error',
    'typescript/no-unnecessary-condition': 'error',
    'max-lines': [
      'error',
      {
        max: 400,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
  },
  overrides: [
    {
      files: ['**/*.{js,jsx,mjs,cjs}'],
      rules: {
        'constructor-super': 'error',
        'getter-return': 'error',
        'no-class-assign': 'error',
        'no-const-assign': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-keys': 'error',
        'no-func-assign': 'error',
        'no-import-assign': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-obj-calls': 'error',
        'no-redeclare': 'error',
        'no-setter-return': 'error',
        'no-this-before-super': 'error',
        'no-unreachable': 'error',
        'no-unsafe-negation': 'error',
        'no-with': 'error',
        'typescript/ban-ts-comment': [
          'error',
          {
            minimumDescriptionLength: 10,
          },
        ],
        'typescript/no-empty-object-type': 'error',
        'eslint-js/no-restricted-syntax': [
          'error',
          {
            selector: 'CallExpression[callee.name="require"]',
            message: 'require() is forbidden. Use static ESM imports.',
          },
          {
            selector: 'ExportNamedDeclaration > ExportSpecifier',
            message:
              'Do not create export proxy declarations. Export symbols where they are declared.',
          },
          {
            selector:
              "CallExpression[callee.object.name='JSON'][callee.property.name='parse'][arguments.0.type='CallExpression'][arguments.0.callee.object.name='JSON'][arguments.0.callee.property.name='stringify']",
            message:
              'Do not use JSON.parse(JSON.stringify(...)) to normalize values. Compare with toEqual directly, or transform only the received value when persistence changed its shape.',
          },
        ],
      },
    },
    {
      files: ['**/*.{ts,tsx,mts,cts}'],
      rules: {
        'typescript/await-thenable': 'error',
        'typescript/ban-ts-comment': [
          'error',
          {
            'ts-ignore': true,
            'ts-expect-error': true,
            'ts-nocheck': true,
            'ts-check': true,
          },
        ],
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'error',
        'typescript/no-confusing-void-expression': 'error',
        'typescript/no-deprecated': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-empty-object-type': [
          'error',
          {
            allowInterfaces: 'with-single-extends',
            allowObjectTypes: 'never',
          },
        ],
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-meaningless-void-operator': 'error',
        'typescript/no-misused-promises': 'error',
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-type-arguments': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-type-parameters': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/no-useless-default-assignment': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/prefer-reduce-type-parameter': 'error',
        'typescript/prefer-return-this-type': 'error',
        'typescript/promise-function-async': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        'typescript/restrict-template-expressions': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNever: false,
            allowNullish: false,
            allowNumber: true,
            allowRegExp: false,
          },
        ],
        'typescript/return-await': ['error', 'error-handling-correctness-only'],
        'typescript/unbound-method': 'error',
        'typescript/use-unknown-in-catch-callback-variable': 'error',
        'no-var': 'error',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'typescript/consistent-return': 'error',
        'typescript/consistent-type-assertions': [
          'error',
          {
            assertionStyle: 'as',
            objectLiteralTypeAssertions: 'never',
          },
        ],
        'typescript/consistent-type-exports': 'error',
        'typescript/consistent-type-imports': [
          'error',
          {
            prefer: 'type-imports',
            disallowTypeAnnotations: true,
            fixStyle: 'separate-type-imports',
          },
        ],
        'typescript/no-unnecessary-qualifier': 'error',
        'typescript/no-unsafe-type-assertion': 'error',
        'typescript/prefer-nullish-coalescing': 'error',
        'typescript/prefer-optional-chain': 'error',
        'typescript/strict-void-return': 'error',
        'eslint-js/no-restricted-syntax': [
          'error',
          {
            selector: 'CallExpression[callee.name="require"]',
            message: 'require() is forbidden. Use static ESM imports.',
          },
          {
            selector: 'ExportNamedDeclaration > ExportSpecifier',
            message:
              'Do not create export proxy declarations. Export symbols where they are declared.',
          },
          {
            selector: 'TSAsExpression[typeAnnotation.type="TSAnyKeyword"]',
            message:
              'Casting to any is forbidden. Use a precise type or validate unknown data first.',
          },
          {
            selector: 'TSAsExpression[typeAnnotation.type="TSNeverKeyword"]',
            message: 'Casting to never is forbidden. Model the impossible state explicitly.',
          },
          {
            selector: "TSAsExpression > TSAsExpression[typeAnnotation.type='TSUnknownKeyword']",
            message:
              'Do not use double assertions through unknown. Model the type or validate the value instead.',
          },
          {
            selector: 'ExportNamedDeclaration[source], ExportAllDeclaration[source]',
            message:
              'Do not re-export from another module. Import from the owning module directly.',
          },
          {
            selector:
              'TSTypeReference[typeName.name=/^(Pick|Omit|Partial|NonNullable)$/], TSExpressionWithTypeArguments[expression.name=/^(Pick|Omit|Partial|NonNullable)$/], TSClassImplements[expression.name=/^(Pick|Omit|Partial|NonNullable)$/]',
            message:
              'Do not use Pick, Omit, Partial, or NonNullable. Write the explicit object shape.',
          },
          {
            selector: 'TSIntersectionType',
            message: 'Do not use intersection types. Write one explicit named shape.',
          },
          {
            selector:
              "CallExpression[callee.object.name='JSON'][callee.property.name='parse'][arguments.0.type='CallExpression'][arguments.0.callee.object.name='JSON'][arguments.0.callee.property.name='stringify']",
            message:
              'Do not use JSON.parse(JSON.stringify(...)) to normalize values. Compare with toEqual directly, or transform only the received value when persistence changed its shape.',
          },
        ],
      },
    },
    {
      files: [
        '**/load-preset-check.ts',
        '**/load-preset-gate-config.ts',
        '**/tests/setup/testDatabase.ts',
      ],
      rules: {
        'aqg/no-dynamic-import': 'off',
      },
    },
    {
      files: [
        '**/load-preset-check.ts',
        '**/load-preset-gate-config.ts',
        '**/preset-runtime.ts',
        '**/public-verify.ts',
        '**/check.ts',
        '**/gate-config.ts',
        '**/tests/setup/testDatabase.ts',
      ],
      rules: {
        'eslint-js/no-restricted-syntax': 'off',
      },
    },
  ],
});
