import type { readAgentQualityGateConfig } from '../verify/config/agent-quality-gate-config.js';
import {
  resolveHealthThresholds,
  resolveLockedQualityRuleNames,
} from '../verify/config/policy.js';

export const AGENT_GUIDE_NAME = 'agent-quality-gate.md';

const QUALITY_CONSTRAINT_GROUPS = [
  {
    rules: ['quality/console-format-placeholders'],
    text: 'Console output: dynamic values require format placeholders with a matching argument count.',
  },
  {
    rules: ['quality/no-empty-extended-interfaces', 'quality/no-useless-exported-type-aliases'],
    text: 'Interfaces and aliases: extended interfaces must add members; exported type aliases must define more than a new name for another type.',
  },
  {
    rules: [
      'quality/no-null-undefined-parameter-union',
      'quality/no-unknown-parameters',
      'quality/no-wide-parameter-unions',
    ],
    text: 'Parameters: use precise implementation types; `unknown` is reserved for type predicates; never combine `null` with `undefined`; unions may exceed two alternatives only when every alternative is literal.',
  },
  {
    rules: [
      'quality/no-indexed-access-types',
      'quality/no-manual-exported-string-literal-unions',
      'quality/require-export-string-literal-catalogs-as-const',
    ],
    text: 'String literal catalogs: indexed access types are forbidden except for the exact form `(typeof identifier)[number]`; declare exported non-empty catalogs as unannotated `as const` tuples and derive their union types from the runtime tuple instead of duplicating them manually.',
  },
  {
    rules: ['quality/no-runtime-in-types-files', 'quality/no-types-in-runtime-files'],
    text: 'Type organization: dedicated type files (`*.d.ts`, `*.d.mts`, `*.d.cts`, `*.types.ts(x)`, `*.contracts.ts(x)`, `*.interfaces.ts(x)`, and `types.ts(x)`) contain only type imports, exports, and declarations; runtime files normally cannot contain top-level types, except for a directly exported companion union of the exact form `(typeof localExportedConst)[number]` derived from an exported `as const` string literal catalog in the same file.',
  },
  {
    rules: ['quality/no-single-use-forwarders'],
    text: 'Functions: inline thin local forwarding functions that have only one caller.',
  },
];

const SYNTAX_CONSTRAINTS = [
  'Lint suppression: Oxlint disable directives are forbidden, and ESLint directives cannot suppress locked rules.',
  'Modules: use static ESM imports and direct exports; `require()`, dynamic `import()`, re-exports, and export proxies are forbidden.',
  'Type assertions: casts to `any` or `never` and double assertions through `unknown` are forbidden; model the type or validate the value instead.',
  'Type shapes: write explicit named shapes instead of `Pick`, `Omit`, `Partial`, `NonNullable`, or intersection types.',
];

function projectPluginSection(projectConfig: ReturnType<typeof readAgentQualityGateConfig>): string[] {
  if (projectConfig.plugins.length === 0) {
    return [];
  }
  return [
    '## Project-specific Oxlint rules',
    '',
    ...projectConfig.plugins.flatMap((plugin) => [
      `- Plugin \`${plugin.name}\`:`,
      ...Object.entries(plugin.rules).map(
        ([rule, severity]) =>
          `  - \`${rule}\`: \`${typeof severity === 'string' ? severity : JSON.stringify(severity)}\``
      ),
    ]),
    '',
  ];
}

function qualityConstraintLines(): string[] {
  const lockedNames = new Set(resolveLockedQualityRuleNames());
  const coveredNames = new Set(QUALITY_CONSTRAINT_GROUPS.flatMap((group) => group.rules));
  for (const name of lockedNames) {
    if (!coveredNames.has(name)) {
      throw new Error(`Missing agent guide constraint for ${name}`);
    }
  }
  for (const name of coveredNames) {
    if (!lockedNames.has(name)) {
      throw new Error(`Agent guide constraint references disabled rule ${name}`);
    }
  }
  return QUALITY_CONSTRAINT_GROUPS.map((group) => `- ${group.text}`);
}

export function renderAgentGuide(
  projectConfig: ReturnType<typeof readAgentQualityGateConfig>,
  packageVersion: string
): string {
  const health = resolveHealthThresholds(projectConfig);
  const lines = [
    '# Code validation rules',
    '',
    `> Generated from locked policy version ${packageVersion}. Do not edit this file. Update it with \`bun run generate-agent-guide\`.`,
    '',
    ...projectPluginSection(projectConfig),
    '## Locked coding constraints',
    '',
    ...SYNTAX_CONSTRAINTS.map((constraint) => `- ${constraint}`),
    ...qualityConstraintLines(),
    '',
    '## Standard checks summarized',
    '',
    '- JavaScript and TypeScript correctness rules reject unreachable, invalid, unused, misleading, or unsafe code.',
    '- TypeScript rules reject unsafe `any` usage, unsafe assertions and operations, floating or misused promises, unnecessary types and conversions, and invalid type structure.',
    '- Source files may contain at most 400 non-blank, non-comment lines.',
    '- Fallow rejects unused files, exports, types, members, and dependencies; unresolved or undeclared imports; dependency and re-export cycles; duplicate exports; stale or unexplained suppressions; thin wrappers; prop drilling; and duplicated prop shapes.',
    '- Duplicate code detection uses mild mode with a minimum of 30 tokens and 3 lines and a maximum duplication threshold of 10%.',
    `- Function complexity limits are cyclomatic \`${String(health.maxCyclomatic)}\`, cognitive \`${String(health.maxCognitive)}\`, and CRAP \`${String(health.maxCrap)}\`.`,
    '',
  ];
  return lines.join('\n');
}
